name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Java et Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Étape 3 : Cacher les dépendances Maven pour accélérer les builds
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Étape 4 : Compiler et exécuter les tests unitaires
      - name: Build and Test
        run: mvn clean verify

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Construire l'image Docker
      - name: Build Docker Image
        run: docker build -t elalamimohamed/meetingplanner-:latest .

      # Étape 3 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 4 : Pousser l'image Docker sur Docker Hub
      - name: Push Docker Image
        run: docker push elalamimohamed/meetingplanner:latest
